//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public string ARTICLES_CODE { get; set; }
        public string ARTICLES_NAME { get; set; }
        public string IMAGES { get; set; }
        public string SUMMARY_CONTENT { get; set; }
        public Nullable<System.DateTime> DATE_SUBMITTED { get; set; }
        public string TYPE_OF_NEWS { get; set; }
        public string CONTENT { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<bool> APPROVED { get; set; }
    
        public virtual LOGIN LOGIN { get; set; }
    }
}
