//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public string ORDERS_NUMBER { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<bool> ACTIVATED { get; set; }
        public Nullable<System.DateTime> DELIVERY_DATE { get; set; }
        public string SHIPPING_ADDRESS { get; set; }
        public string NOTE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual LOGIN LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
    }
}
