//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public string PRODUCTS_CODE { get; set; }
        public string PRODUCTS_NAME { get; set; }
        public string IMAGES { get; set; }
        public string SUMMARY_CONTENT { get; set; }
        public Nullable<System.DateTime> DATE_SUBMITTED { get; set; }
        public int TYPE_CODE { get; set; }
        public string CONTENT { get; set; }
        public string ACCOUNT { get; set; }
        public string dvt { get; set; }
        public Nullable<bool> APPROVED { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> SALE { get; set; }
        public string PRODUCER { get; set; }
    
        public virtual LOGIN LOGIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
        public virtual TYPE_OF_PRODUCTS TYPE_OF_PRODUCTS { get; set; }
    }
}
